/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SignMetadata } from '../types/sign';

export const CORE_SIGNS: SignMetadata[] = [
  {
    id: 'help',
    label: 'Help',
    category: 'essential',
    icon: '🆘',
    description: 'Closed fist with thumb extended upward ("A" handshape) resting on or lifting from open palm.',
    instruction: 'Make a fist with thumb pointing upward (thumbs up), held prominently in front of chest.',
    clinicalContext: 'Used when patient needs immediate assistance, repositioning, or attention.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'doctor',
    label: 'Doctor',
    category: 'medical',
    icon: '👨‍⚕️',
    description: 'Bent fingers tapping wrist (checking pulse) or "D" handshape (index pointed up, thumb touching other curled fingers).',
    instruction: 'Point index finger straight up with thumb touching middle and ring finger tips, or tap your wrist pulse.',
    clinicalContext: 'Request to speak with attending physician or specialist.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'pain',
    label: 'Pain',
    category: 'medical',
    icon: '⚡',
    description: 'Both index fingers pointed toward each other with twisting motion, or single index finger pointing and pulsating at pain site.',
    instruction: 'Extend index finger out horizontally while keeping other fingers closed in a fist, moving toward area of discomfort.',
    clinicalContext: 'Critical signal for acute pain, cramps, pressure, or surgical site irritation.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'water',
    label: 'Water',
    category: 'essential',
    icon: '💧',
    description: '"W" handshape: Index, middle, and ring fingers extended upright and spread apart, thumb pinning pinky.',
    instruction: 'Hold up 3 fingers (index, middle, ring) upright in a "W" shape near your chin or chest.',
    clinicalContext: 'Thirst, dry throat, NPO verification, or swallowing aid needed.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'extended',
      ring: 'extended',
      pinky: 'curled',
    },
  },
  {
    id: 'medicine',
    label: 'Medicine',
    category: 'medical',
    icon: '💊',
    description: 'Middle finger bent downward slightly into palm as if crushing a pill, or cupped hand motion to mouth.',
    instruction: 'Open palm facing up or bring fingertips gently toward lips as if taking a pill or tablet.',
    clinicalContext: 'Scheduled medication query, analgesics, nausea pills, or IV drip check.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'emergency',
    label: 'Emergency',
    category: 'medical',
    icon: '🚨',
    description: '"E" handshape (curled fingers touching thumb) shaken side to side rapidly, or vigorous open wave.',
    instruction: 'Hold hand with all fingers curled into palm and shake hand horizontally with urgency.',
    clinicalContext: 'Code alarm, sudden breathing difficulty, chest tightness, or critical distress.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'yes',
    label: 'Yes',
    category: 'essential',
    icon: '✅',
    description: 'Fist nodding up and down from the wrist like a head nodding affirmatively.',
    instruction: 'Form a closed fist and tilt wrist up and down slowly, affirming the doctor\'s question.',
    clinicalContext: 'Patient confirmation for consent, comfort checks, or triage questions.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'no',
    label: 'No',
    category: 'essential',
    icon: '❌',
    description: 'Index and middle fingers extended together and snapping down to meet the thumb (like a bird beak closing).',
    instruction: 'Bring index and middle finger tips down to tap against thumb tip repeatedly.',
    clinicalContext: 'Negative response, refusal of action, denial of symptom or allergy.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'extended',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'where',
    label: 'Where',
    category: 'question',
    icon: '❓',
    description: 'Index finger pointing upward and shaking back and forth side to side with questioning brow.',
    instruction: 'Hold index finger straight up and pivot it side to side gently.',
    clinicalContext: 'Asking where family is, where the pain is located, or where the nurse went.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'thank-you',
    label: 'Thank You',
    category: 'essential',
    icon: '🙏',
    description: 'Flat open hand with fingers together, moving from chin/lips outward forward toward doctor.',
    instruction: 'Open all fingers flat together, palm facing inward toward chest, then moving outward.',
    clinicalContext: 'Gratitude to care team, acknowledges finished procedure.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'extended',
      ring: 'extended',
      pinky: 'extended',
    },
  },
];

export const SUPPORTED_LANGUAGES = [
  { code: 'sw', name: 'Kiswahili (Kenya)', flag: '🇰🇪', speechCode: 'sw-KE' },
  { code: 'ksl', name: 'KSL Gloss (Kenyan Sign Language)', flag: '🇰🇪🤟', speechCode: 'sw-KE' },
  { code: 'en', name: 'English (US)', flag: '🇺🇸', speechCode: 'en-US' },
  { code: 'es', name: 'Español', flag: '🇪🇸', speechCode: 'es-ES' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', speechCode: 'fr-FR' },
  { code: 'ar', name: 'العربية (Arabic)', flag: '🇸🇦', speechCode: 'ar-SA' },
  { code: 'zh', name: '中文 (Mandarin)', flag: '🇨🇳', speechCode: 'zh-CN' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', speechCode: 'de-DE' },
  { code: 'hi', name: 'हिन्दी (Hindi)', flag: '🇮🇳', speechCode: 'hi-IN' },
  { code: 'ja', name: '日本語 (Japanese)', flag: '🇯🇵', speechCode: 'ja-JP' },
  { code: 'asl', name: 'ASL Clinical Gloss', flag: '🤟', speechCode: 'en-US' },
];

export const QUICK_MEDICAL_PHRASES = [
  { text: 'Unasikia maumivu wapi?', sender: 'doctor' as const },
  { text: 'Daktari anakuja kutoa msaada sasa.', sender: 'doctor' as const },
  { text: 'Kunywa maji na dawa hii.', sender: 'doctor' as const },
  { text: 'Where does it hurt?', sender: 'doctor' as const },
  { text: 'Are you experiencing severe pain?', sender: 'doctor' as const },
  { text: 'I am bringing your medicine now.', sender: 'doctor' as const },
  { text: 'Please drink some water.', sender: 'doctor' as const },
  { text: 'Help, I need the nurse!', sender: 'patient' as const },
  { text: 'Nina maumivu makali sana kifuani.', sender: 'patient' as const },
  { text: 'Asante sana kwa msaada wako.', sender: 'patient' as const },
];
