/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SignMetadata } from '../types/sign';

export const CORE_SIGNS: SignMetadata[] = [
  {
    id: 'help',
    label: 'Help',
    category: 'essential',
    icon: 'help',
    description: 'Closed fist with thumb extended upward ("A" handshape) resting on or lifting from open palm.',
    instruction: 'Make a fist with thumb pointing upward (thumbs up), held prominently in front of chest.',
    clinicalContext: 'Used when patient needs immediate assistance, repositioning, or attention.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'doctor',
    label: 'Doctor',
    category: 'medical',
    icon: 'doctor',
    description: 'Bent fingers tapping wrist (checking pulse) or "D" handshape (index pointed up, thumb touching other curled fingers).',
    instruction: 'Point index finger straight up with thumb touching middle and ring finger tips, or tap your wrist pulse.',
    clinicalContext: 'Request to speak with attending physician or specialist.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'pain',
    label: 'Pain',
    category: 'medical',
    icon: 'pain',
    description: 'Both index fingers pointed toward each other with twisting motion, or single index finger pointing and pulsating at pain site.',
    instruction: 'Extend index finger out horizontally while keeping other fingers closed in a fist, moving toward area of discomfort.',
    clinicalContext: 'Critical signal for acute pain, cramps, pressure, or surgical site irritation.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'water',
    label: 'Water',
    category: 'essential',
    icon: 'water',
    description: '"W" handshape: Index, middle, and ring fingers extended upright and spread apart, thumb pinning pinky.',
    instruction: 'Hold up 3 fingers (index, middle, ring) upright in a "W" shape near your chin or chest.',
    clinicalContext: 'Thirst, dry throat, NPO verification, or swallowing aid needed.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'extended',
      ring: 'extended',
      pinky: 'curled',
    },
  },
  {
    id: 'medicine',
    label: 'Medicine',
    category: 'medical',
    icon: 'medicine',
    description: 'Middle finger bent downward slightly into palm as if crushing a pill, or cupped hand motion to mouth.',
    instruction: 'Open palm facing up or bring fingertips gently toward lips as if taking a pill or tablet.',
    clinicalContext: 'Scheduled medication query, analgesics, nausea pills, or IV drip check.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'emergency',
    label: 'Emergency',
    category: 'medical',
    icon: 'emergency',
    description: '"E" handshape (curled fingers touching thumb) shaken side to side rapidly, or vigorous open wave.',
    instruction: 'Hold hand with all fingers curled into palm and shake hand horizontally with urgency.',
    clinicalContext: 'Dharura / Urgent alert, sudden distress or critical complication.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'blood',
    label: 'Blood',
    category: 'medical',
    icon: 'blood',
    description: 'Flat left forearm held horizontal while dominant right index finger traces downward indicating bleeding or blood loss.',
    instruction: 'Extend dominant index finger down across opposite forearm indicating bleeding.',
    clinicalContext: 'Damu / Hemorrhage, trauma bleeding, or IV blood draw.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'stomach',
    label: 'Stomach',
    category: 'medical',
    icon: 'stomach',
    description: 'Both open palms gently circulating over lower abdomen signaling acute nausea or stomach cramps.',
    instruction: 'Move open flat hand gently over stomach area.',
    clinicalContext: 'Tumbo Kuumwa / Gastrointestinal pain, food poisoning, or pregnancy cramps.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'extended',
      ring: 'extended',
      pinky: 'extended',
    },
  },
  {
    id: 'breathing',
    label: 'Breathing',
    category: 'medical',
    icon: 'breathing',
    description: 'Both open hands placed in front of chest rise and sink in synchronized respiratory motion.',
    instruction: 'Raise and lower open hands against chest mimicking respiration.',
    clinicalContext: 'Kupumua / Dyspnea, asthma flare-up, COPD, or chest congestion.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'extended',
      ring: 'extended',
      pinky: 'extended',
    },
  },
  {
    id: 'examine',
    label: 'Examine',
    category: 'medical',
    icon: 'examine',
    description: '"C" or pinch handshape moves forward methodically as clinician inspects patient.',
    instruction: 'Pinch thumb and index together moving forward in testing gesture.',
    clinicalContext: 'Chunguza / Diagnostic exam, blood pressure check, or physical inspection.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'fever',
    label: 'Fever',
    category: 'medical',
    icon: 'fever',
    description: 'Back of right hand touches forehead feeling for high body temperature.',
    instruction: 'Touch back of fingers gently against forehead.',
    clinicalContext: 'Homa / Pyrexia, elevated temperature, chills, or malaria symptoms.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'extended',
      ring: 'extended',
      pinky: 'extended',
    },
  },
  {
    id: 'hospital',
    label: 'Hospital',
    category: 'medical',
    icon: 'hospital',
    description: 'Right index finger traces cross emblem upon upper left arm or shoulder.',
    instruction: 'Trace a small plus or cross sign on opposite shoulder.',
    clinicalContext: 'Hospitali / Referral transfer, ward admission, or clinical facility.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'injection',
    label: 'Injection',
    category: 'medical',
    icon: 'injection',
    description: 'Right thumb and index mimic syringe pressing into upper arm.',
    instruction: 'Form syringe motion with index and thumb pressed against shoulder.',
    clinicalContext: 'Sindano / Vaccination, IM pain injection, or IV medication push.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'headache',
    label: 'Headache',
    category: 'medical',
    icon: 'headache',
    description: 'Right index finger points and rotates near temple signaling head pain.',
    instruction: 'Tap index finger gently near side of temple.',
    clinicalContext: 'Kichwa Kinauma / Migraine, cranial pressure, or stress headache.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'food',
    label: 'Food',
    category: 'essential',
    icon: 'food',
    description: 'Right hand fingertips gathered together tap mouth twice denoting meal schedule.',
    instruction: 'Bring closed fingertips toward lips twice.',
    clinicalContext: 'Chakula / Meal schedule, enteral nutrition, or dietary restriction.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'sleep',
    label: 'Sleep',
    category: 'essential',
    icon: 'sleep',
    description: 'Right palm rests flat against side of tilted head denoting resting state.',
    instruction: 'Tilt head slightly against flat open palm.',
    clinicalContext: 'Usingizi / Patient rest, sedation check, or sleep post-surgery.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'extended',
      ring: 'extended',
      pinky: 'extended',
    },
  },
  {
    id: 'yes',
    label: 'Yes',
    category: 'essential',
    icon: 'yes',
    description: 'Fist nodding up and down from the wrist like a head nodding affirmatively.',
    instruction: 'Form a closed fist and tilt wrist up and down slowly, affirming the doctor\'s question.',
    clinicalContext: 'Patient confirmation for consent, comfort checks, or triage questions.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'curled',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'no',
    label: 'No',
    category: 'essential',
    icon: 'no',
    description: 'Index and middle fingers extended together and snapping down to meet the thumb (like a bird beak closing).',
    instruction: 'Bring index and middle finger tips down to tap against thumb tip repeatedly.',
    clinicalContext: 'Negative response, refusal of action, denial of symptom or allergy.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'extended',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'where',
    label: 'Where',
    category: 'question',
    icon: 'where',
    description: 'Index finger pointing upward and shaking back and forth side to side with questioning brow.',
    instruction: 'Hold index finger straight up and pivot it side to side gently.',
    clinicalContext: 'Asking where family is, where the pain is located, or where the nurse went.',
    fingerStateHint: {
      thumb: 'curled',
      index: 'extended',
      middle: 'curled',
      ring: 'curled',
      pinky: 'curled',
    },
  },
  {
    id: 'thank-you',
    label: 'Thank You',
    category: 'essential',
    icon: 'thank-you',
    description: 'Flat open hand with fingers together, moving from chin/lips outward forward toward doctor.',
    instruction: 'Open all fingers flat together, palm facing inward toward chest, then moving outward.',
    clinicalContext: 'Gratitude to care team, acknowledges finished procedure.',
    fingerStateHint: {
      thumb: 'extended',
      index: 'extended',
      middle: 'extended',
      ring: 'extended',
      pinky: 'extended',
    },
  },
];

export const SUPPORTED_LANGUAGES = [
  { code: 'sw', name: 'Kiswahili (Kenya)', flag: 'KE', speechCode: 'sw-KE' },
  { code: 'ksl', name: 'KSL Gloss (Kenyan Sign Language)', flag: 'KSL', speechCode: 'sw-KE' },
  { code: 'en', name: 'English (US)', flag: 'US', speechCode: 'en-US' },
  { code: 'es', name: 'Español', flag: 'ES', speechCode: 'es-ES' },
  { code: 'fr', name: 'Français', flag: 'FR', speechCode: 'fr-FR' },
  { code: 'ar', name: 'العربية (Arabic)', flag: 'SA', speechCode: 'ar-SA' },
  { code: 'zh', name: '中文 (Mandarin)', flag: 'CN', speechCode: 'zh-CN' },
  { code: 'de', name: 'Deutsch', flag: 'DE', speechCode: 'de-DE' },
  { code: 'hi', name: 'हिन्दी (Hindi)', flag: 'IN', speechCode: 'hi-IN' },
  { code: 'ja', name: '日本語 (Japanese)', flag: 'JP', speechCode: 'ja-JP' },
  { code: 'asl', name: 'ASL Clinical Gloss', flag: 'ASL', speechCode: 'en-US' },
];

export const QUICK_MEDICAL_PHRASES = [
  { text: 'Unasikia maumivu wapi?', sender: 'doctor' as const },
  { text: 'Daktari anakuja kutoa msaada sasa.', sender: 'doctor' as const },
  { text: 'Kunywa maji na dawa hii.', sender: 'doctor' as const },
  { text: 'Where does it hurt?', sender: 'doctor' as const },
  { text: 'Are you experiencing severe pain?', sender: 'doctor' as const },
  { text: 'I am bringing your medicine now.', sender: 'doctor' as const },
  { text: 'Please drink some water.', sender: 'doctor' as const },
  { text: 'Help, I need the nurse!', sender: 'patient' as const },
  { text: 'Nina maumivu makali sana kifuani.', sender: 'patient' as const },
  { text: 'Asante sana kwa msaada wako.', sender: 'patient' as const },
];
